import type { Metadata } from "next";
import "./globals.css";
import { natoSansKR } from "@/fonts/fonts";
import { cn } from "@/lib/utils";
import { Providers } from "../providers/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(natoSansKR.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
