import type { Metadata } from "next";
import "./globals.css";
import { natoSansKR } from "@/fonts/fonts";
import { cn } from "@/lib/utils";
import { Providers } from "../providers/providers";
import { EnvData } from "@/contants/env-data";
import { unstable_noStore as noStore } from "next/cache";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (EnvData.NEXT_ENV === "ingress") noStore();
  return (
    <html lang="en">
      <body className={cn(natoSansKR.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
