name: hs-client CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: kaburi/hs-client:latest, kaburi/hs-client:${{ github.run_number }}

      - name: Checkout click-helms repository
        uses: actions/checkout@v3
        with:
          repository: KaburiCoder/click-helms
          token: ${{ secrets.CLICK_HELMS_REPO_TOKEN }} # GitHub 토큰
          path: .
          ref: main # 기본 브랜치를 명시적으로 지정 (main이 기본 브랜치일 경우)

      - name: Update YAML file
        run: |
          sed -i '/hsClient:/,/service:/s/version: ".*"/version: "${{ github.run_number }}"/' hs/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git add hs/values.yaml
          git commit -m "Update version to ${{ github.run_number }}"
          git push
